export enum CatalogueTypeEnum {
  COMPANIES_PERSON_TYPE = 'COMPANIES_PERSON_TYPE',
  BLOOD_TYPE = 'BLOOD_TYPE',
  GENDER = 'GENDER',
  ETHNIC_ORIGIN = 'ETHNIC_ORIGIN',
  IDENTIFICATION_TYPE = 'IDENTIFICATION_TYPE',
  MARITAL_STATUS = 'MARITAL_STATUS',
  SEX = 'SEX',
  COURSES_AREA = 'COURSES_AREA',
  COURSES_CERTIFICATION_TYPE = 'COURSES_CERTIFICATION_TYPE',
}

export enum CatalogueStateEnum {
  ENABLED = 'enabled',
  DISABLED = 'disabled',
}

export enum UsersIdentificationTypeStateEnum {
  IDENTIFICATION = '1',
  PASSPORT = '2',
}

export enum CatalogueEnum {
  INDICATOR_SUBACTIVITY = 'INDICATOR_SUBACTIVITY',
  INSTITUTIONAL_STRATEGIC_PLAN = 'INSTITUTIONAL_STRATEGIC_PLAN',
  STRATEGIC_AXIS = 'STRATEGIC_AXIS',
  STRATEGY = 'STRATEGY',
  CONTINENT = 'CONTINENT',
  COUNTRY = 'COUNTRY',
  PROVINCE = 'PROVINCE',
  CANTON = 'CANTON',
  PARISH = 'PARISH',
  POA = 'POA',
  UNIT = 'UNIT',
  PND_OBJECTIVE = 'PND_OBJECTIVE',
  PND_POLICE = 'PND_POLICE',
  EXPENSE_TYPE = 'EXPENSE_TYPE',
  EXPENSE_GROUP = 'EXPENSE_GROUP',
}

export enum RoutesEnum {
  NEW = 'new',
}
