export enum CatalogueTypeEnum {
  //COMPANIES 
  COMPANIES_PERSON_TYPE = 'COMPANIES_PERSON_TYPE',
  COMPANIES_TYPE = 'COMPANIES_TYPE',
  //USERS
  BLOOD_TYPE = 'USERS_BLOOD_TYPE',
  GENDER = 'USERS_GENDER',
  ETHNIC_ORIGIN = 'USERS_ETHNIC_ORIGIN',
  IDENTIFICATION_TYPE = 'USERS_IDENTIFICATION_TYPE',
  MARITAL_STATUS = 'USERS_MARITAL_STATUS',
  SEX = 'USERS_SEX',
  //COURSES
  COURSES_AREA = 'COURSES_AREA',
  COURSES_CERTIFICATION_TYPE = 'COURSES_CERTIFICATION_TYPE',
  //SKILLS
  SKILLS_TYPE = 'SKILLS_TYPE',
  //ACADEMIC CARRER
  ACADEMIC_FORMATIONS_CAREER = 'ACADEMIC_FORMATIONS_CAREER',
  ACADEMIC_FORMATIONS_PROFESSIONAL_DEGREE = ' ACADEMIC_FORMATIONS_PROFESSIONAL_DEGREE',
  ACADEMIC_FORMATIONS_INSTITUTION = 'ACADEMIC_FORMATIONS_INSTITUTION',
  COURSES_TYPE = 'COURSES_TYPE',
  EXPERIENCES_AREA = ' EXPERIENCES_AREA',
  //Languages
  LANGUAGE_IDIOM = 'LANGUAGE_IDIOM',
  LANGUAGE_READ_LEVEL = 'LANGUAGE_READ_LEVEL',
  LANGUAGE_SPOKEN_LEVEL = 'LANGUAGE_SPOKEN_LEVEL',
  LANGUAGE_WRITTEN_LEVEL = ' LANGUAGE_WRITTEN_LEVEL',
  //
  CONTACT_EMAIL = 'CONTACT_EMAIL',
  CONTACT_NAME = ' CONTACT_NAME',
  CONTACT_PHONE = 'CONTACT_PHONE',
  INSTITUTION ='INSTITUTION',
  POSITION = ' POSITION',
}

export enum CatalogueStateEnum {
  ENABLED = 'enabled',
  DISABLED = 'disabled', 
}

export enum UsersIdentificationTypeStateEnum {
  IDENTIFICATION = '1',
  PASSPORT = '2',
}

export enum CatalogueEnum {
  INDICATOR_SUBACTIVITY = 'INDICATOR_SUBACTIVITY',
  INSTITUTIONAL_STRATEGIC_PLAN = 'INSTITUTIONAL_STRATEGIC_PLAN',
  STRATEGIC_AXIS = 'STRATEGIC_AXIS',
  STRATEGY = 'STRATEGY',
  CONTINENT = 'CONTINENT',
  COUNTRY = 'COUNTRY',
  PROVINCE = 'PROVINCE',
  CANTON = 'CANTON',
  PARISH = 'PARISH',
  POA = 'POA',
  UNIT = 'UNIT',
  PND_OBJECTIVE = 'PND_OBJECTIVE',
  PND_POLICE = 'PND_POLICE',
  EXPENSE_TYPE = 'EXPENSE_TYPE',
  EXPENSE_GROUP = 'EXPENSE_GROUP',
}

export enum RoutesEnum {
  NEW = 'new',
}
